<?xml version="1.0" encoding="UTF-8"?>
<StyledLayerDescriptor version="1.0.0"
  xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd"
  xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<NamedLayer>
    <Name>CLC12_DOM</Name>
    <UserStyle>
      <Name>CLC12_DOM</Name>
      <Title>CLC12_DOM</Title>
      <Abstract>Style pour CLC2012 DOM</Abstract>
      <FeatureTypeStyle>
        <Rule><Title>1110 - Tissu urbain continu</Title><Name>1110 - Tissu urbain continu</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1110</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E6004D</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#E6004D</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>1120 - Tissu urbain discontinu</Title><Name>1120 - Tissu urbain discontinu</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1120</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FF0000</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FF0000</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>1210 - Zones industrielles ou commerciales et installations publiques</Title><Name>1210 - Zones industrielles ou commerciales et installations publiques</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1210</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#CC4DF2</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#CC4DF2</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>1220 - Réseaux routier et ferroviaire et espaces associés</Title><Name>1220 - Réseaux routier et ferroviaire et espaces associés</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1220</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#CC0000</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#CC0000</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>1230 - Zones portuaires</Title><Name>1230 - Zones portuaires</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1230</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E6CCCC</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#E6CCCC</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>1240 - Aéroports</Title><Name>1240 - Aéroports</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1240</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E6CCE6</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#E6CCE6</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>1310 - Extraction de matériaux</Title><Name>1310 - Extraction de matériaux</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1310</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#A600CC</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#A600CC</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>1320 - Décharges</Title><Name>1320 - Décharges</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1320</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#A64D00</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#A64D00</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>1330 - Chantiers</Title><Name>1330 - Chantiers</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1330</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FF4DFF</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FF4DFF</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>1410 - Espaces verts urbains</Title><Name>1410 - Espaces verts urbains</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1410</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FFA6FF</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FFA6FF</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>1420 - Equipements sportifs et de loisirs</Title><Name>1420 - Equipements sportifs et de loisirs</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>1420</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FFE6FF</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FFE6FF</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2111 - Terres arables hors périmètres d'irrigation</Title><Name>2111 - Terres arables hors périmètres d'irrigation</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2111</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FFFFA8</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FFFFA8</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2112 - Canne à sucre</Title><Name>2112 - Canne à sucre</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2212</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FFD37F</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FFD37F</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
		<Rule><Title>2120 - Périmètres irrigués en permanence</Title><Name>2120 - Périmètres irrigués en permanence</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2120</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FFFF00</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FFFF00</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2130 - Rizières</Title><Name>2130 - Rizières</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2130</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E6E600</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#E6E600</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2210 - Vignobles</Title><Name>2210 - Vignobles</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2210</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E68000</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#E68000</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2221 - Vergers et petits fruits</Title><Name>2221 - Vergers et petits fruits</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2221</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#F2A64D</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#F2A64D</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2222 - Bananeraies</Title><Name>2222 - Bananeraies</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2222</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FFFFBE</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FFFFBE</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2223 - Palmeraies</Title><Name>2223 - Palmeraies</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2223</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FFFF73</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FFFF73</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2224 - Caféiers</Title><Name>2224 - Caféiers</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2224</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FFAA00</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FFAA00</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
		<Rule><Title>2230 - Oliveraies</Title><Name>2230 - Oliveraies</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2230</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E6A600</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#E6A600</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
		<Rule><Title>2310 - Prairies et autres surfaces toujours en herbe à usage agricole</Title><Name>2310 - Prairies et autres surfaces toujours en herbe à usage agricole</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2310</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E6E64D</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#E6E64D</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2410 - Cultures annuelles associées à des cultures permanentes</Title><Name>2410 - Cultures annuelles associées à des cultures permanentes</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2410</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FFE6A6</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FFE6A6</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2420 - Systèmes culturaux et parcellaires complexes</Title><Name>2420 - Systèmes culturaux et parcellaires complexes</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2420</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#FFE64D</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#FFE64D</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2430 - Surfaces essentiellement agricoles, interrompues par des espaces naturels importants</Title><Name>2430 - Surfaces essentiellement agricoles, interrompues par des espaces naturels importants</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2430</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E6CC4D</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#E6CC4D</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>2440 - Territoires agroforestiers</Title><Name>2440 - Territoires agroforestiers</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>2440</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#F2CCA6</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#F2CCA6</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3111 - Forêts de feuillus</Title><Name>3111 - Forêts de feuillus</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3111</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#80FF00</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#80FF00</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3112 - Mangroves</Title><Name>3112 - Mangroves</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3112</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#00A884</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#00A884</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
		<Rule><Title>3120 - Forêts de conifères</Title><Name>3120 - Forêts de conifères</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3120</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#00A600</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#00A600</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3130 - Forêts mélangées</Title><Name>3130 - Forêts mélangées</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3130</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#4DFF00</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#4DFF00</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3210 - Pelouses et pÃ¢turages naturels</Title><Name>3210 - Pelouses et pÃ¢turages naturels</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3210</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#CCF24D</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#CCF24D</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3220 - Landes et broussailles</Title><Name>3220 - Landes et broussailles</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3220</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#A6FF80</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#A6FF80</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3230 - Végétation sclérophylle</Title><Name>3230 - Végétation sclérophylle</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3230</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#A6E64D</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#A6E64D</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3240 - Forêt et végétation arbustive en mutation</Title><Name>3240 - Forêt et végétation arbustive en mutation</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3240</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#A6F200</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#A6F200</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3310 - Plages, dunes et sable</Title><Name>3310 - Plages, dunes et sable</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3310</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E6E6E6</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#E6E6E6</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3320 - Roches nues</Title><Name>3320 - Roches nues</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3320</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#CCCCCC</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#CCCCCC</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3330 - Végétation clairsemée</Title><Name>3330 - Végétation clairsemée</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3330</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#CCFFCC</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#CCFFCC</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3340 - Zones incendiées</Title><Name>3340 - Zones incendiées</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3340</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#000000</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#000000</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>3350 - Glaciers et neiges éternelles</Title><Name>3350 - Glaciers et neiges éternelles</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>3350</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#A6E6CC</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#A6E6CC</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>4110 - Marais intérieurs</Title><Name>4110 - Marais intérieurs</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>4110</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#A6A6FF</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#A6A6FF</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>4120 - Tourbières</Title><Name>4120 - Tourbières</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>4120</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#4D4DFF</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#4D4DFF</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>4210 - Marais maritimes</Title><Name>4210 - Marais maritimes</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>4210</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#CCCCFF</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#CCCCFF</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>4220 - Marais salants</Title><Name>4220 - Marais salants</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>4220</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E6E6FF</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#E6E6FF</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>4230 - Zones intertidales</Title><Name>4230 - Zones intertidales</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>4230</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#A6A6E6</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#A6A6E6</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>5111 - Cours et voies d'eau</Title><Name>5111 - Cours et voies d'eau</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>5111</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#00CCF2</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#00CCF2</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>5112 - Cours et voies d'eau temporaires</Title><Name>5112 - Cours et voies d'eau temporaires</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>5112</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#BEE8FF</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#BEE8FF</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
		<Rule><Title>5120 - Plans d'eau</Title><Name>5120 - Plans d'eau</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>5120</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#80F2E6</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#80F2E6</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>5210 - Lagunes littorales</Title><Name>5210 - Lagunes littorales</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>5210</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#00FFA6</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#00FFA6</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>5220 - Estuaires</Title><Name>5220 - Estuaires</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>5220</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#A6FFE6</CssParameter><CssParameter name="fill-opacity">1</CssParameter></Fill><Stroke><CssParameter name="stroke">#A6FFE6</CssParameter><CssParameter name="stroke-opacity">1</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
        <Rule><Title>5230 - Mers et océans</Title><Name>5230 - Mers et océans</Name><ogc:Filter><ogc:PropertyIsEqualTo><ogc:PropertyName>CODE_12</ogc:PropertyName><ogc:Literal>5230</ogc:Literal></ogc:PropertyIsEqualTo></ogc:Filter><PolygonSymbolizer><Fill><CssParameter name="fill">#E6F2FF</CssParameter><CssParameter name="fill-opacity">0</CssParameter></Fill><Stroke><CssParameter name="stroke">#E6F2FF</CssParameter><CssParameter name="stroke-opacity">0</CssParameter><CssParameter name="stroke-width">0.5</CssParameter></Stroke></PolygonSymbolizer></Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>